/** Declaration file generated by dts-gen */

export = listr;

declare class listr {
    constructor(...args: any[]);

    add(...args: any[]): void;

    render(...args: any[]): void;

    run(...args: any[]): void;

    setRenderer(...args: any[]): void;

}
